Fix TypeScript syntax error in AddMealModal
Fixed triple closing angle bracket (>>>) to double (>>) in useState generic type declaration on line 26.

Error was:
  useState<Array<number | string>>>([])

Fixed to:
  useState<Array<number | string>>([])

This syntax error was introduced during the PR merge and caused:
  ReferenceError: number is not defined